@backend_HostAddress = http://localhost:9999

###
POST {{backend_HostAddress}}/payments
Content-Type: application/json

{
    "correlationId": "a725a9a5-172a-438d-9798-046df3387dd0",
    "amount": 234.56
}

###

GET {{backend_HostAddress}}/payments-summary

###

POST {{backend_HostAddress}}/purge-payments

###