@backend_HostAddress = http://localhost:8080

###
POST {{backend_HostAddress}}/payments
Content-Type: application/json

{
    "correlationId": "19b08677-48fd-4ca8-ac41-c602c5a31fb8",
    "amount": 234.56
}

###

GET {{backend_HostAddress}}/payments-summary

###

POST {{backend_HostAddress}}/purge-payments

###